version: '3.8'
services:
  app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - ${PWD}/public/images:/app/public/images:ro
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host
    depends_on:
      - server

  server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
      - ${PWD}/public/images:/app/public/images:ro
    environment:
      - NODE_ENV=development
    command: node src/server/index.js
